### ISSUE TITLE
Getting Field Consistency not found in type config.NoSQL

### ISSUE THREAD

**Issue by tarun-discovery** [banzaicloud/banzai-charts#1319]
**Describe the bug**

For cadence charts - None of My pods are starting up
I am getting below error
  line 33: field consistency not found in type config.NoSQL
  line 42: field consistency not found in type config.NoSQL

**Steps to reproduce the issue:**

Just follow instructions to install helm chart, and i get this error

**Expected behavior**

Pods should start successfully

**Screenshots**

**Additional context**

**Comment by pt-mpb** [comment]
Any luck with this @tarun-discovery ?

I'm having the exact same issue.

> **Describe the bug**
> 
> For cadence charts - None of My pods are starting up I am getting below error line 33: field consistency not found in type config.NoSQL line 42: field consistency not found in type config.NoSQL
> 
> **Steps to reproduce the issue:**
> 
> Just follow instructions to install helm chart, and i get this error
> 
> **Expected behavior**
> 
> Pods should start successfully
> 
> **Screenshots**
> 
> **Additional context**

**Comment by bdelano** [comment]
this issue is caused by `consistency` no longer being a valid configuration parameter... 
until banzai fixes the issue the only way to resolve it is to:
* clone the banzai git repository
* go to the cadence root and remove any references to `consistency` from `values.yaml`
* run a helm update from that source directory 
`helm upgrade {your_cadence_service_name} -f {your_values_file} . -n {your_namespace}`

**Comment by akijakya** [comment]
Solved in version [0.23.1](https://github.com/banzaicloud/banzai-charts/releases/tag/cadence%2F0.23.1)
