### ISSUE TITLE
Vault pods not starting

### ISSUE THREAD

**Issue by rahmnathan** [banzaicloud/banzai-charts#612]
So this is likely user error, but I can't figure out what I'm missing. I've deployed the helm chart via the following command:

`helm install -n vault-operator-test --namespace vault-operator-test banzaicloud-stable/vault-operator --set etcd-operator.enabled=true`

Everything appears to start up properly. I then try to create a Vault instance using the files located here - https://github.com/banzaicloud/bank-vaults/tree/master/operator/deploy.

When using 'cr.yaml', no pods are deployed. The output from the following command does not display any errors:

`kubectl -n vault-operator-test describe vaults.vault.banzaicloud.com vault`

A log entry shows up in the operator pod with the following:

`{"level":"info","ts":1547574045.4465306,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-operator-test","Request.Name":"vault"}`

When using 'cr-etc-ha.yaml', the etcd pods are deployed, but still no vault instance. There are a few errors in the etcd logs:

`2019-01-15 17:55:56.069395 W | etcdserver: failed to reach the peerURL(https://etcd-cluster-t6pg4bdjh2.etcd-cluster.vault-operator-test.svc:2380) of member a7867c2eb3a27ad6 (Get https://etcd-cluster-t6pg4bdjh2.etcd-cluster.vault-operator-test.svc:2380/version: dial tcp: lookup etcd-cluster-t6pg4bdjh2.etcd-cluster.vault-operator-test.svc on 10.43.0.10:53: no such host)
2019-01-15 17:55:56.069420 W | etcdserver: cannot get the version of member a7867c2eb3a27ad6 (Get https://etcd-cluster-t6pg4bdjh2.etcd-cluster.vault-operator-test.svc:2380/version: dial tcp: lookup etcd-cluster-t6pg4bdjh2.etcd-cluster.vault-operator-test.svc on 10.43.0.10:53: no such host)`

Should a pod be starting here, or am I missing something?

**Comment by rahmnathan** [comment]
I'm also seeing this in the vault operator logs when trying to create an instance with 'cr-etcd-ha.yaml':

`{"level":"error","ts":1547576147.5178995,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"vault-controller","request":"vault-operator-test/vault","error":"failed to get configmap: ConfigMap \"vault-configurer\" not found","stacktrace":"github.com/banzaicloud/bank-vaults/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}`

**Comment by baluchicken** [comment]
Hi @rahmnathan 
If you take a look on the helm [chart](https://github.com/banzaicloud/banzai-charts/blob/5516b605af515d6d4d85068cd154a1a5dfdbd0da/vault-operator/templates/sa.yaml#L4) you are deployed, it creates a Service Account for Vault using the name specified by you in the helm command, in your case `vault-operator-test`.

Next take a look on the [cr.yaml](https://github.com/banzaicloud/bank-vaults/blob/2983a7dde81ac01e89e1e13a3d71fa32533f4a5b/operator/deploy/cr.yaml#L16) you mentioned. It also has a field ServiceAccount which is by default set to `vault` so in your case the operator creates the Vault StatefulSet for you but it cannot start a pod because it could not find the right ServiceAccount.

Please rewrite our example [cr.yaml](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml) file to point to the right ServiceAccount in your case it's `vault-operator-test`. 

Because you are not using the `default` namespace please remember that to use the proper namespace while creating the cr. In your case `kubectl create -n vault-operator-test -f <pathtothecr.yaml>`
Thanks for submitting the issue, I hope I answered all your questions. Please let me know if you have more.

**Comment by rahmnathan** [comment]
@baluchicken I really appreciate the quick response. That was the issue! After updating the cr-etcd-ha.yaml to have the correct service account, my vault pods are starting! I'll keep pushing forward and open a new issue if I get stuck.

Thanks again

**Comment by rahmnathan** [comment]
@baluchicken Unfortunately, I didn't get very far. I got to the UI using the port-forward command, but I can't seem to get logged in. I grabbed the root token from the following command:

`kubectl -n vault-operator-test get secrets vault-unseal-keys -o yaml` 

But when trying to log in I'm getting permission denied. The status is 'unsealed', so I'm not sure what I'm missing here.

**Comment by bonifaido** [comment]
@rahmnathan, you can get the unseal key with:

```kubectl get secrets vault-unseal-keys -o jsonpath={.data.vault-root} | base64 -D | pbcopy```

then navigate to the UI:

```open https://localhost:8200/ui```

and enter the password from the clipboard. With these steps I can't reproduce the error. Were you doing the same steps?

**Comment by rahmnathan** [comment]
@bonifaido The part I was missing was decoding the base64 token. In my previous Vault deployments, I thought I had used the base64 token directly without decoding it. I'll close this now. Thanks again for your help.
