### ISSUE TITLE
Access vault outside of the cluster?

### ISSUE THREAD

**Issue by misanche** [banzaicloud/banzai-charts#839]
Hi, first of all awesome work, I'm trying to do the following:

Once the operator has been deployed, I try to change the vault service, from ClusterIP to LoadBalancer to get the external url:
`kubectl patch service vault -p '{"spec": {"type": "LoadBalancer" }}' -n vault`

I try to see the output of the service:
`kubectl get service vault -n vault `
```
NAME    TYPE           CLUSTER-IP      EXTERNAL-IP                                                               PORT(S)                                                       AGE
vault   LoadBalancer   100.70.250.60   ab4398c797c6f11e9bc1702e8ffb0aea-1719069693.us-east-2.elb.amazonaws.com   8200:31455/TCP,8201:31633/TCP,9091:31866/TCP,9125:31376/TCP   5d

```
But then is changed again to:
NAME    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                               AGE
vault   ClusterIP   100.70.250.60   <none>        8200/TCP,8201/TCP,9091/TCP,9125/TCP   5d

Is there any way to change the service type from ClusterIP to LoadBalancer?

**Comment by bonifaido** [comment]
Hi @misanche,

first of all, thanks! :)

The service type can be configured in the CR itself since it is always reconciled in the operator it will change it back to the configured type from any manually changed value. Please use the [serviceType](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml#L47) field for configuring it through the operator.
