### ISSUE TITLE
[chart/banzaicloud-stable/thanos] Helm 3 template validation errors on rule installation

### ISSUE THREAD

**Issue by jshrack-ssi** [banzaicloud/banzai-charts#982]
**Describe the bug**

When installing the thanos chart with Helm 3 the following validation errors fail the installation:

coalesce.go:196: warning: cannot overwrite table with non table for annotations (map[])
coalesce.go:165: warning: skipped value for objstore: Not a table.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec): unknown field "resources" in io.k8s.api.core.v1.PodSpec, ValidationError(StatefulSet.spec.template.spec): unknown field "secretName" in io.k8s.api.core.v1.PodSpec, ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec]

**Steps to reproduce the issue:**
1) Enable rule component.
2) Install chart using Helm 3 with the following command: helm install -f values.yaml thanos banzaicloud-stable/thanos

**Expected behavior**
Successful installation of rule statefulset.

**Screenshots**

**Additional context**
If rule component is disabled then the rest of the chart components install successfully.

**Comment by AlexDHoffer** [comment]
Helm 3 is complaining because "resources", "secretName", and "serviceName" are not available fields in statefulsets.spec.template.spec, as per the Kubernetes [https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podspec-v1-core](docs).

I believe the culprit for this occurring on Helm 3 is that Helm has grown stricter in its manifest validation with time. Take a look at this [https://github.com/helm/helm/issues/5750](issue) to see an example of a case where a Helm upgrade (2.13 -> 2.14) caused what normally worked to fail.

I am working on a PR to address this, since I need the BanzaiCloud Thanos Ruler templates to be Helm 3-compliant.
