### ISSUE TITLE
Cadence unable to increase replica count of History service without the service thrashing

### ISSUE THREAD

**Issue by mkevanz** [banzaicloud/banzai-charts#994]
**Describe the bug**
Out of the box, the chart works fine with single replicas per service, but when you increase the number of History shards and monitor the logs, you will see that the History service starts thrashing. You can see this by looking at the "sharditem_created_count" in the Prometheus metrics and tailing the logs for errors.

**Steps to reproduce the issue:**

Spin up new cluster. Increase history service replicas to 2. Tail logs and monitor the sharditem_created_count.

**Expected behavior**
The service should not be thrashing. I believe this has something to do with how the DNS configuration is specified.

**Comment by mfateev** [comment]
By design number of shards is immutable after the cluster has started. We might consider supporting "shard splitting" in the future. But it wouldn't be as simple as changing the number of shards in config as it would imply data migration.

We have plans to ignore shard count changes after a cluster is initialized to avoid confusion and operational issues. But for know just document that it is not allowed to change this value once the cluster is deployed.

**Comment by mkevanz** [comment]
@mfateev The replicas I am referencing specifically refers to node replicas of the History service in Cadence - not shards. Whenever I spin up more than 1 node using the configuration specified in this chart, the service is still functionality, but we see a high rate of shard adds / deletes. Talking to you and Samar, we discovered this is why my workflows were latent and timing out. I am running an identical setup to this chart.
